// Mocks generated by Mockito 5.4.6 from annotations
// in faciale/test/liveness_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:faciale/features/attendance/face_detector_service.dart' as _i2;
import 'package:google_mlkit_face_detection/google_mlkit_face_detection.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FaceDetectorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFaceDetectorService extends _i1.Mock
    implements _i2.FaceDetectorService {
  MockFaceDetectorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Face>> detectFaces(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#detectFaces, [imagePath]),
            returnValue: _i3.Future<List<_i4.Face>>.value(<_i4.Face>[]),
          )
          as _i3.Future<List<_i4.Face>>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
