// Mocks generated by Mockito 5.4.6 from annotations
// in faciale/test/features/attendance/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:faciale/features/attendance/attendance_repository.dart' as _i2;
import 'package:faciale/features/attendance/offline_storage_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AttendanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceRepository extends _i1.Mock
    implements _i2.AttendanceRepository {
  MockAttendanceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> checkIn(
    String? imagePath, {
    String? forceType,
    bool? isOffline = false,
    String? orgId,
    String? userId,
    String? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkIn,
              [imagePath],
              {
                #forceType: forceType,
                #isOffline: isOffline,
                #orgId: orgId,
                #userId: userId,
                #timestamp: timestamp,
              },
            ),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [OfflineStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineStorageService extends _i1.Mock
    implements _i4.OfflineStorageService {
  MockOfflineStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveScan(
    String? imagePath,
    String? forceType, {
    String? orgId,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveScan,
              [imagePath, forceType],
              {#orgId: orgId, #userId: userId},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeScan(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#removeScan, [imagePath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  int getPendingScansCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingScansCount, []),
            returnValue: 0,
          )
          as int);

  @override
  List<Map<String, dynamic>> getPendingScans() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingScans, []),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  _i3.Future<void> clearScans() =>
      (super.noSuchMethod(
            Invocation.method(#clearScans, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
